version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-app
    depends_on:
      - mongodb
      - mysql
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://root:example@mongodb:27017
      KNEX_URL: mysql://appuser:apppass@mysql:3306/appdb
    command: ["npm", "run", "start"]

volumes:
  mongo_data:
  mysql_data:

